# Generated by Django 4.2.4 on 2023-08-19 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='phone_number',
            new_name='mobile_no',
        ),
    ]
