# Generated by Django 4.2.4 on 2023-08-19 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_phone_number_users_mobile_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='usr_id',
            new_name='user_id',
        ),
    ]
